version: "3"
services:
  nodejs:
    image: nodejs:v1
    build: node
    hostname: nodejs
    container_name: nodejs
    depends_on:
      - node_mysql
    ports:
      - "8080:8080"
    volumes:
      - ./app/:/home/node/
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    networks:
      - code-network
    command:
      ["npm","run","start"]
    logging:
      driver: json-file
      options:
        max-size: 20k
        max-file: '3'
  node_mysql:
    image: mysql:5.7
    container_name: mysql 
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_another_username
      MYSQL_PASSWORD: your_another_username
      MYSQL_ROOT_PASSWORD: your_root_passwd
    networks:
      - code-network
    logging:
      driver: json-file
      options:
        max-size: 20k
        max-file: '3'
networks:
  code-network:
    name: code-network
    driver: bridge
