version: '3.2'
services:
  haproxy:
    image: haproxy:lts
    container_name: haproxy
    restart: always
    network_mode: host
    sysctls:
      - net.core.somaxconn=2000
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /data/haproxy/config/:/etc/haproxy/
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
    command: ["-f", "/etc/haproxy/haproxy.cfg"]
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m
